### ISSUE TITLE
Show people in a region as a bulleted list within the popup

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location-display#133]
After fixing #123, it's showing that there are "2 people" but we should be instead showing a list of the people, like:

```
* firstPerson
* secondPerson
```

_Originally posted by @jywarren in https://github.com/publiclab/leaflet-blurred-location-display/pull/123#issuecomment-896154396_

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/128918873-f3e4d08f-8665-40b7-be92-3224f17a90f4.png)

**Comment by jywarren** [comment]
That's odd. There should be a list already:

https://github.com/publiclab/leaflet-blurred-location-display/blob/bb806bb0e055d8358717ae1af1268959a2ea715f/src/ui/gridCenterRectangle.js#L74-L90

**Comment by jywarren** [comment]
Aha! I think what happens is that it shows the count if there is no "url" property of the people. But on PublicLab.org, we do pass that. So it should be OK when run over there. I think we just need to release a new version here.

**Comment by jywarren** [comment]
Published as v1.3.1! https://www.npmjs.com/package/leaflet.blurred-location-display cc @daemon1024

**Comment by daemon1024** [comment]
We will need to reopen this. 

Ref https://github.com/publiclab/plots2/pull/10033#issuecomment-900495239

it seems that the parsed_data you mentioned here, is only for temporary use.

https://github.com/publiclab/leaflet-blurred-location-display/blob/d5cff82f61bd31cbb58dd11ed6ed221639ef9a26/src/blurredLocationDisplay.js#L147

we use it here, what we store in the markers object is https://github.com/publiclab/leaflet-blurred-location-display/blob/d5cff82f61bd31cbb58dd11ed6ed221639ef9a26/src/blurredLocationDisplay.js#L164-L168 
is the leaflet marker object mapped to id. So there's no URL at all and hence no list of people names.

**Comment by jywarren** [comment]
Aha! Ok, excellent debugging! Hopefully we can solve this with a PR here and then through LEL to plots2 again? 

Great detective work, @daemon1024!!!

**Comment by daemon1024** [comment]
Sure, I am on it. Can be assigned to me :)
