### ISSUE TITLE
Add/remove markers as zoom level change .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-blurred-location-display#18]
Reference : https://github.com/publiclab/leaflet-blurred-location-display/issues/9#issuecomment-383973448

> So does this make sense? That in this library, as you zoom in, some locations appear only within some zoom levels, that are close to the precision they were entered in? If they have lots of precision, they might appear in many zoom levels, but if they are very imprecise (highly blurred), they would be hidden once you zoom in too far.

> We could write a test to check for this -- so it would start the map up, go to a certain zoom level, and check what's visible, then zoom in further and check again, for 3 or 4 zoom levels. Then we could write the functions of this library to ensure that the markers are properly displayed for those given zoom levels.

**Comment by jywarren** [comment]
@icarito can you see about enabling CORS for requests to /api/ on plots2? (@sagarpreet-chadha maybe you can reach out to icarito in chat if he needs more info?)

**Comment by jywarren** [comment]
Yes, this makes sense - it's like a filter that accepts and outputs an array, and each API call we run the returned markers through it!

**Comment by jywarren** [comment]
We can write a simple test to show that only the correct precisions are passed through the filter -- very test-able!

**Comment by sagarpreet-chadha** [comment]
What should be the logic to filter coordinates @jywarren ? Is the one i proposed above makes sense ? Thanks !

**Comment by jywarren** [comment]
yes, i think so. It could be a simple conditional if the precision falls
within the specified range. The filter could be configured with
`.filter(top, bottom)` perhaps? or `filter(markers, top, bottom)`?

**Comment by icarito** [comment]
Hey I went to enable CORS but found - **Access-Control-Allow-Origin** : * - already present

**Comment by icarito** [comment]
Just for consistency and in case it helps I've allowed CORS to our staging instances! Let me know if something more is needed.

**Comment by sagarpreet-chadha** [comment]
This was the error : 
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ... 
(Reason: CORS request not http).`

It is working now @icarito . Thank you 😄 !
