### ISSUE TITLE
Adding travis CI to the repo

### ISSUE THREAD

**Issue by mridulnagpal** [publiclab/leaflet-blurred-location-display#2]
Can you tell me how to do it, like you did it n the previous repo

**Comment by jywarren** [comment]
Oops - i had to rename the repo to "leaflet-blurred-location-display" for
consistency. But i'll add travis, you just need to add a .travis.yml file,
like:
https://github.com/publiclab/leaflet-blurred-location/blob/master/.travis.yml

**Comment by jywarren** [comment]
OK! https://travis-ci.org/publiclab/leaflet-blurred-location-display

**Comment by mridulnagpal** [comment]
Perfect, closing this one for now!! Cheers!!
