### ISSUE TITLE
Establish a simple way to instantiate individual locations and collections

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-blurred-location-display#38]
Hi @jywarren ,

We need to figure a way of passing static locations (instead of fetching from some API) to the LBLD API , right ?

Kindly confirm this. Thanks 😄 !

**Comment by jywarren** [comment]
Yes well we should be able to parsed a Json file whether it's static or
dynamic - here I think we should just be able to declare var location = new
L.BlurredLocation, or something. See the constructor in leaflet
DistortableImage as an example!

**Comment by jywarren** [comment]
Or here's a good example
https://github.com/publiclab/leaflet-multispectral/blob/main/README.md#usage

**Comment by sagarpreet-chadha** [comment]
On it 😄 !

**Comment by sagarpreet-chadha** [comment]
@jywarren , 
Check this out  😄 : 
https://publiclab.github.io/leaflet-blurred-location-display/examples/example.html
