### ISSUE TITLE
Define a source URL parameter to point the library at the API

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-blurred-location-display#39]
We need to tell the API parameters format to the user in README (it has to be of a specific format) . Also the API should be of following format : 

<img width="789" alt="screenshot 2019-02-18 at 8 00 18 pm" src="https://user-images.githubusercontent.com/14952645/52957514-d6f62c80-33b7-11e9-8ec0-a5a865dd18d6.png">

**Comment by sagarpreet-chadha** [comment]
The API's format should be  : 
`"https://publiclab.org/api/srch/nearbyPeople?nwlat=" + NWlat + "&selat=" + SElat + "&nwlng=" + NWlng + "&selng=" + SElng`

**Comment by jywarren** [comment]
Great! Could we pass a json parsing function into the lib to handle the response, and use a default that expects GeoJSON, but show how to override it to receive PL API formatted data?

**Comment by sagarpreet-chadha** [comment]
Great idea :) 
Can i implement this after PR #42  gets merged ? 
In PR #42 , i have passes source_url as a parameter to LBLD API and used default function for parsing . Thank you !

**Comment by jywarren** [comment]
I'm going to review 42 next, yeah i thought of that connected to this too. Thanks!!!
