### ISSUE TITLE
Adding basic html layout for it to work

### ISSUE THREAD

**Issue by mridulnagpal** [publiclab/leaflet-blurred-location-display#4]
Do I copy the html code from the leaflet-blurred-location repo, as we will be need the objects to display location.

**Comment by jywarren** [comment]
You could copy much of it, but you can also use a more basic Leaflet map
example from leafletjs.org -- and use a list of locations in an array.

**Comment by mridulnagpal** [comment]
I think this is done, closing issue

**Comment by jywarren** [comment]
great!
