### ISSUE TITLE
 example of zooming out to show that high precision markers can be made to disappear

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-blurred-location-display#43]
The current demo is here : https://publiclab.github.io/leaflet-blurred-location-display/examples/example.html

<img width="1278" alt="screenshot 2019-02-21 at 10 28 57 am" src="https://user-images.githubusercontent.com/14952645/53144754-88b57900-35c3-11e9-941a-3a3417a337cc.png">

High precision marker with coordinates for example : [23.1234 , 76.1234] .

@jywarren ...What do we wish to show in the new example ? Should we make another HTML file to demonstrate this ? Thanks 😄 !

**Comment by jywarren** [comment]
Hi Sagarpreet!!

I guess we either need to develop a standard for when high precision
markers are hidden at zoomed out zoom levels (and how that works; when do
they start getting hidden?) and/or establish a means to set what range of
zooms a given marker should be shown at.

Maybe we can establish a reasonable default range but let people override
it?

**Comment by sagarpreet-chadha** [comment]
Yes it makes sense to give power to override the range of zoom-levels where 'x' precision marker should be visible  👍  . However we should also make a good standardized default range as well .

**Comment by jywarren** [comment]
Yes! Let's work towards this and make it clear in the README too. 👍 🎉
