### ISSUE TITLE
color code the markers and coordinate text so that people can distinguish the different precisions visually

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-blurred-location-display#44]
> Can we also open a new issue to color code the markers and coordinate text so that people can distinguish the different precisions visually?
> 
> And one to default to geoJson for Json parsing?

- [x] Give different colors to markers according to their precision .

(kindly elaborate these 😄 !) 
- [x]  coordinate text 

- [ ] one to default to geoJson for Json parsing

**Comment by jywarren** [comment]
So if we color code the markers by precision, blue could be .00x, red .0x,
green .000x and so on, we could color the text in the demo to match so you
can see what coordinates correspond to which markers based on color. What
do you think?

For geoJson, I'm just thinking we can make the default follow the geoJson
standard. Does it seem like a good idea?

**Comment by sagarpreet-chadha** [comment]
Great idea 😄 ! 
Should we color code markers for both static/local-data markers and remote-data-fetched markers ? 

And --- What is the geoJSON standard ? Also by geoJSON here , what do we mean ?  

Thank you !
