### ISSUE TITLE
write tests that assert the markers are shown or hidden as in the new example code!

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-blurred-location-display#45]
Hi @jywarren ,

Can you give some examples from other repositories ? (similar examples would also work 😄 !)

Thank you 🎈 !

**Comment by jywarren** [comment]
Sure! Jasmine is nice for this kind of testing - you can use jQuery to count elements at different stages:

https://github.com/publiclab/inline-markdown-editor/blob/e2b0c19e1075b475d015df429f1b10f0b6a9ef20/spec/javascripts/replacement_spec.js#L14-L32

Take a look and it'd allow us to manipulate the map and then at different moments, check for the existence or styling (using `$('selector').hasClass('myClass');`) of different HTML elements.
