### ISSUE TITLE
 "recently used locations"  feature

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-blurred-location-display#73]
- 1.) A second one is - tell me what you think, but the idea of "recently used locations" as a way to speed up the Leaflet Blurred Location modal; we could, on plots2, look up recently added location tags and offer them as a way to quickly add location.

- 2.) We might also use the most recent location as the default location that appears when you open the LBL modal, so it sort of assumes "near the last place you input".

Hi @jywarren ,
I like this idea very much 😄 . Let's discuss here how to do it on plots2 ? 

So should we make a function in plots2 that calculates the recent 5 unique places (we will get latitude and longitude also from the power tags) used by current user  ?
or
 calculates the recent 5 unique places used in general in publiclab.org  ?
or
maybe recent 5 places which are used maximum number of times in publiclab.org  ?

What do you think ?

**Comment by sagarpreet-chadha** [comment]
Logically, i think it would be great if we can calculate the last 5 latest locations (coordinates and/or placename) used by a user and show it on LBL model on plots2 . 
And by default the location of map will be the last one used . What do you think  @jywarren ?

**Comment by jywarren** [comment]
:-) this is awesome.
